### PR TITLE
Paging support in PDF added

### PR DESCRIPTION
**Pull request by gyfke**
## content: url()

Added support for images in css content property so you can reuse embedded images
Example:

```css
    img.logo {
        content: url('data:image/jpeg;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAA...
    }
```

```html
...
    <img class="logo">
...
```

## Paging in PDF

Implemented css-style page-break-inside. It supports two values: **auto** (default) and **avoid**

1.	With default values there is no rules defined to transfer html-blocks or words to the next page. And pages can be splitted right through the text
 

2.	With **td { page-break-inside: avoid; }** words which are located in the edge of pages will be transferred to the new page.
The same is for th, p, span and I guess for any text in any other tags (though I’ve checked only aforementioned)

3.	With **table { page-break-inside: avoid; }** if table row is not fitted to the page, then the whole row will be transferred to the next page.
If row is bigger than page then it doesn’t make sense to transfer it and the value of page-break-inside will be ignored.

Known cosmetic issues:

1.	If table's page-break-inside=auto and cell’s page-break-inside=avoid then an empty part of table cell can be rendered at the end of page
And all the text will be transferred to the next one
 

2.	If table's page-break-inside=avoid and the row is bigger than the rest of page but can be fitted to the next page it will be transferred to the next page and will leave a lot of space on the previous one

## Headers and footers
Added support for **position: fixed**, elements with fixed position are rendered on every page and can be used as headers/footers/watermarks.
It ignores page margins, so if you need to place 50px-height header and footer on the page with 20px margins you need to set top/bottom margins to 70px to leave proper margins for the main content. Example:
```c#
var config = new PdfGenerateConfig()
{
    MarginBottom = 70,
    MarginLeft = 20,
    MarginRight = 20,
    MarginTop = 70,
};
...
```

```css
.header {
    position: fixed;
    left: 20px;
    top: 20px;
}

.footer{
    position: fixed;
    left: 20px;
    top: 750px;
}
```

```html
<body>
    <div class="header">
        logo
    </div>
    <div class="footer">
        disclaimer
    </div>

    <p>
        page content...
...
```

image

### CODE REVIEW

**Comment by ArthurHub** [comment]
NICE!
Great work!
Can I interest you in taking this project as a direct contributor?

**Comment by michalczukm** [comment]
@ArthurHub could you publish nuget package update with this fix :) ?

**Comment by Ixonal** [comment]
I'm looking to get this functionality as well, so it'd be much appreciated if the nuget package were to be updated.

**Comment by netmann** [comment]
page-break-inside: avoid doesn't include `<br/>` tag inside `<p></p>` element during page height calculation.
I would be grateful for fix

**Comment by amreimer** [comment]
I downloaded the demo code, which includes all the changes described here, however the resulting PDFs do not break as the description states.  I used the "Breaking pages 1" and "Breaking Pages 2" sample code.  I would be EXTREMELY excited if this code did work as described and illustrated above, it is exactly what I'm looking for.  Until then I am trying all kinds of styles/methods.

I even downloaded all the code and built it myself without nuget with the same results.

renderer-1
renderer-2
renderer-3

**Comment by ElVisPL** [comment]
Doesn't work for me either.
I cloned repository and built HtmlRenderer myself - still page break inside <tr> tag

**Comment by HumanRob** [comment]
@amreimer yes I've also been unable to get it to work - even when downloading and building the code myself. `table { page-break-inside: avoid; }` seems to work as expected, but I can't get `td { page-break-inside: avoid; }` to work at all - also tried it with span and p elements. 

I'd be happy to look into fixing this myself, but because I can't get the feature to work at all it's kind of hard to know where to begin!

For the time being, to prevent words getting cut in half across pages I've had to wrap each paragraph in a table with `page-break-inside: avoid;` set, which almost but not quite achieves the same result at the cost of horribly mangling my html!

If anyone could provide steps to get this feature working, or even ideas on where I should start bug hunting, please let me know.

**Comment by PawelMaj** [comment]
@HumanRob @amreimer Hey! I have recently decided to join this project and started looking into the page-breaking code in specific (I have my own self interests in making it work haha). That being said, I think the words will break a page correctly if the immediate parent element has that attribute on it and if the parent element is smaller than the size of the page.

Should work
`<td style="page-break-inside: avoid;">Hello</td> `

Will fail
`<td style="page-break-inside: avoid;"><span>Hello</span></td>`

Unfortunately I am a bit busy the next few weeks, but when I am free I will do my best to implement some generic page breaking that works with nested elements. Also if you only really care about making sure words are not split in half you can change the following code:

CssRect.cs ln307

From:
```
if (!box.IsFixed && box.PageBreakInside == CssConstants.Avoid)
{
     word.BreakPage();
}
```

To:
```
if (!box.IsFixed)
{
     word.BreakPage();
}
```

If I am correct (I may be wrong, I have only started to get into this code) this change will make sure that no words will ever be split on a page break.

**Comment by grandpaSam** [comment]
@PawelMaj I believe you actually mean:

CssLayoutEngine.cs ln307

**Comment by luislhg** [comment]
It is on CssLayoutEngine.cs ln307
And PawelMaj works as expected! Finally got this working, thanks! :)

**Comment by SwiftDoge** [comment]
I was having the issue of pages being split right through the text and adding this bit of css seems to have fixed the problem`table, tr, td {
page-break-inside: avoid;
			font-size: 14px;
		}`. This works without updating the html-rendered to the 1.5.1-beta1 version which is quite confusing to me, how is that possible? Did I just get lucky with my particular pdf? (Just a disclaimer I have close to no idea how this html-renderer works so apologies if this is a silly question )

**Comment by grandpaSam** [comment]
@gyfke 
I seem to be having and issue with fixed position. On the second page my header seems to draw over the content. I would like to have a header on each page which I believe the position fixed attribute is supposed to accomplish. This seems to work well on the first page where I can apply a margin on the body. But on the second page the margin no longer is applied and the header will draw over the content of the page. Am I using position fixed incorrectly?

**Comment by cjfjones** [comment]
@gyfke @grandpaSam - I'm having exactly the same issue, whereby on the first page, the margins are in relation to the fixed content (i.e. the header and footer). On the subsequent pages the margins are in relation to the page itself, therefore my subsequent pages have overlapping objects.

**Comment by vip32** [comment]
@ArthurHub  is this available in current 1.5.0.6?

**Comment by grandpaSam** [comment]
I noticed that the example program has the same header margin problem as in the i described in my previous comment.

**Comment by emilmork** [comment]
Is there any chance this changes with `page-break` will get to an actual nuget package ? :)

Great work with this package anyway 👍

**Comment by ksingamreddy** [comment]
For _page-break_  I tried with following code 
```
td { page-break-inside: avoid; }
table { page-break-inside: avoid; }
```
which is working perfectly but I am getting some additional extra edges at end of the page as shown in the attachment.

edges

Is there any way to get rid of extra edges ?

**Comment by RylaiSlyfe** [comment]
Bumping this. Am using the 1.5.1 prerelease and the page break for tables is working as expected, but with normal text it's still cut off

**Comment by HenningKlokkeraasen** [comment]
I experience the same issue as RylaiSlyfe.
I worked around it by wrapping all texts in a \<table>, and styling it with
        table,
        th,
        td {
            page-break-inside: avoid;
        }

**Comment by Murphybro2** [comment]
I have the temporary solution of wrapping my text in tables. Not ideal to be honest....

**Comment by karritos** [comment]
Woow, works for me. 
I used the third option 
`table { 
     page-break-inside: avoid;
}`
And I updated in NuGet pakages:

- [HtmlRenderer.Core 1.5.1-beta1](https://www.nuget.org/packages/HtmlRenderer.Core/1.5.1-beta1)
- [HtmlRenderer.PdfSharp 1.5.1-beta1](https://www.nuget.org/packages/HtmlRenderer.PdfSharp/1.5.1-beta1)

This in the work project.

**Comment by dlaczny** [comment]
@ksingamreddy did you find out how to get rid of this edges?

**Comment by ksingamreddy** [comment]
@dlaczny we replaced HTML tables with <div>s to get rid of the edges.

**Comment by Stepnicka** [comment]
> @dlaczny we replaced HTML tables with divs to get rid of the edges.

How did you manage to position your divs? I cant get absolute positioning, floats, flex or grids working in the renderer.

**Pull request merged**
