### PR TITLE
New csproj format support and netstandard support

### PR DESCRIPTION
**Pull request by wieslawsoltes**
This PR is done and ready for review/merge.

Changes:
* Port library projects to new csproj format.
* Add `netstadnard2.0` and `.NET Core 2.0` support.
* Remove nuspec files and move all properties to csproj and props files.
* Use common `Build\Version.props` props file instead of `SharedAssemblyInfo.cs` for version management.
* Automate NuGet package creation on `Release` builds .
* Produce appveyor NuGet package  artifacts.
* Remove `nuget.exe` from repository. VS2017 can automatically restore and for appyeyor downloads latest from NuGet site.
* Source Archive is automatically added when doing GitHub releases so it was removed from build scripts.
* Demo apps are automatically uploaded to appyeyor artifacts so build scripts for demos have been removed.

The changes require Visual Studio 2017 to build solution but produced libraries and NuGet packages will maintain the original .NET 2.0 compatibility.

Latest build artifacts: https://ci.appveyor.com/project/ArthurHub/html-renderer/build/artifacts

### CODE REVIEW

**Comment by ohaucke** [comment]
Wouldn't it be better to set `GenerateAssemblyInfo` to `true` in the csproj files?
If it's set to `false`, the `AssemblyVersion` and `FileVersion` of the binaries is set to `0.0.0.0` and this could interfere with some installers (iirc: msi packages relay on this number to identify if a file needs to be updated).

**Comment by wieslawsoltes** [comment]
@ohaucke see the version.props file. The versions are set there.

**Comment by ohaucke** [comment]
@wieslawsoltes I know but with `GenerateAssemblyInfo = false` the binaries doesn't get set this values.

`GenerateAssemblyInfo = true`
true

`GenerateAssemblyInfo = false`
false

**Comment by wieslawsoltes** [comment]
@ohaucke yes you are right. Will make this change.

**Comment by wieslawsoltes** [comment]
@ohaucke Fixed the AssemblyInfo.

**Comment by AwsomeCode** [comment]
Why this one is closed?

**Comment by Wingjam** [comment]
I need the netstandard support, when this will be available? Thanks

**Pull request closed without merging**
